
//dialCodeTable1 globals
var dialCodeTable1_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable1_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable1_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable1_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable1_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable1_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable1_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable1_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable1_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable1_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable1_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable1_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable1_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable1_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable1_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable1_total = [0, dialCodeTable1_1, dialCodeTable1_2, dialCodeTable1_3, dialCodeTable1_4, dialCodeTable1_5, dialCodeTable1_6, dialCodeTable1_7, dialCodeTable1_8, dialCodeTable1_9, dialCodeTable1_10, dialCodeTable1_11, dialCodeTable1_12, dialCodeTable1_13, dialCodeTable1_14, dialCodeTable1_15],
//dialCodeTable2 globals
        dialCodeTable2_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable2_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable2_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable2_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable2_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable2_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable2_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable2_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable2_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable2_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable2_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable2_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable2_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable2_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable2_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable2_total = [0, dialCodeTable2_1, dialCodeTable2_2, dialCodeTable2_3, dialCodeTable2_4, dialCodeTable2_5, dialCodeTable2_6, dialCodeTable2_7, dialCodeTable2_8, dialCodeTable2_9, dialCodeTable2_10, dialCodeTable2_11, dialCodeTable2_12, dialCodeTable2_13, dialCodeTable2_14, dialCodeTable2_15],
//dialCodeTable3 globals
        dialCodeTable3_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable3_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable3_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable3_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable3_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable3_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable3_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable3_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable3_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable3_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable3_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable3_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable3_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable3_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable3_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable3_total = [0, dialCodeTable3_1, dialCodeTable3_2, dialCodeTable3_3, dialCodeTable3_4, dialCodeTable3_5, dialCodeTable3_6, dialCodeTable3_7, dialCodeTable3_8, dialCodeTable3_9, dialCodeTable3_10, dialCodeTable3_11, dialCodeTable3_12, dialCodeTable3_13, dialCodeTable3_14, dialCodeTable3_15],
//dialCodeTable4 globals
        dialCodeTable4_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable4_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable4_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable4_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable4_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable4_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable4_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable4_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable4_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable4_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable4_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable4_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable4_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable4_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable4_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable4_total = [0, dialCodeTable4_1, dialCodeTable4_2, dialCodeTable4_3, dialCodeTable4_4, dialCodeTable4_5, dialCodeTable4_6, dialCodeTable4_7, dialCodeTable4_8, dialCodeTable4_9, dialCodeTable4_10, dialCodeTable4_11, dialCodeTable4_12, dialCodeTable4_13, dialCodeTable4_14, dialCodeTable4_15],
//dialCodeTable5 globals
        dialCodeTable5_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable5_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable5_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable5_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable5_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable5_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable5_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable5_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable5_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable5_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable5_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable5_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable5_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable5_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable5_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable5_total = [0, dialCodeTable5_1, dialCodeTable5_2, dialCodeTable5_3, dialCodeTable5_4, dialCodeTable5_5, dialCodeTable5_6, dialCodeTable5_7, dialCodeTable5_8, dialCodeTable5_9, dialCodeTable5_10, dialCodeTable5_11, dialCodeTable5_12, dialCodeTable5_13, dialCodeTable5_14, dialCodeTable5_15],
//home code tables 6 globals
        dialCodeTable6_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable6_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable6_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable6_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable6_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable6_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable6_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable6_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable6_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable6_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable6_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable6_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable6_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable6_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable6_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable6_total = [0, dialCodeTable6_1, dialCodeTable6_2, dialCodeTable6_3, dialCodeTable6_4, dialCodeTable6_5, dialCodeTable6_6, dialCodeTable6_7, dialCodeTable6_8, dialCodeTable6_9, dialCodeTable6_10, dialCodeTable6_11, dialCodeTable6_12, dialCodeTable6_13, dialCodeTable6_14, dialCodeTable6_15],
//dct 7
        dialCodeTable7_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable7_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable7_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable7_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable7_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable7_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable7_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable7_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable7_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable7_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable7_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable7_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable7_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable7_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable7_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable7_total = [0, dialCodeTable7_1, dialCodeTable7_2, dialCodeTable7_3, dialCodeTable7_4, dialCodeTable7_5, dialCodeTable7_6, dialCodeTable7_7, dialCodeTable7_8, dialCodeTable7_9, dialCodeTable7_10, dialCodeTable7_11, dialCodeTable7_12, dialCodeTable7_13, dialCodeTable7_14, dialCodeTable7_15],
///dct 8 
        dialCodeTable8_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable8_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable8_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable8_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable8_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable8_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable8_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable8_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable8_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable8_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable8_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable8_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable8_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable8_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable8_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable8_total = [0, dialCodeTable8_1, dialCodeTable8_2, dialCodeTable8_3, dialCodeTable8_4, dialCodeTable8_5, dialCodeTable8_6, dialCodeTable8_7, dialCodeTable8_8, dialCodeTable8_9, dialCodeTable8_10, dialCodeTable8_11, dialCodeTable8_12, dialCodeTable8_13, dialCodeTable8_14, dialCodeTable8_15],
//dialCodeTable9 globals
        dialCodeTable9_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable9_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable9_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable9_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable9_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable9_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable9_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable9_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable9_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable9_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable9_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable9_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable9_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable9_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable9_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable9_total = [0, dialCodeTable9_1, dialCodeTable9_2, dialCodeTable9_3, dialCodeTable9_4, dialCodeTable9_5, dialCodeTable9_6, dialCodeTable9_7, dialCodeTable9_8, dialCodeTable9_9, dialCodeTable9_10, dialCodeTable9_11, dialCodeTable9_12, dialCodeTable9_13, dialCodeTable9_14, dialCodeTable9_15],
//dialCodeTable10 globals
        dialCodeTable10_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable10_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable10_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable10_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable10_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable10_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable10_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable10_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable10_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable10_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable10_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable10_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable10_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable10_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable10_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
//get all of the entries in one array - much easier to work with. the first element is the current entry we are working with
        dialCodeTable10_total = [0, dialCodeTable10_1, dialCodeTable10_2, dialCodeTable10_3, dialCodeTable10_4, dialCodeTable10_5, dialCodeTable10_6, dialCodeTable10_7, dialCodeTable10_8, dialCodeTable10_9, dialCodeTable10_10, dialCodeTable10_11, dialCodeTable10_12, dialCodeTable10_13, dialCodeTable10_14, dialCodeTable10_15],
//dct 11
        dialCodeTable11_1 = [">", "0", "- default -", "0", "dct", "7", "0", "0", "0", "", "", "0", ""],
        dialCodeTable11_2 = ["", "1", "123", "0", "dct", "7", "3", "0", "ac", "", "", "0", ""],
        dialCodeTable11_3 = ["", "2", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable11_4 = ["", "3", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable11_5 = ["", "4", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable11_6 = ["", "5", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable11_7 = ["", "6", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable11_8 = ["", "7", "", "", "", "", "", "", "", "", "", "", ""],
        dialCodeTable11_9 = ["", "8", "n0x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable11_10 = ["", "9", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable11_11 = ["", "10", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable11_12 = ["", "11", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable11_13 = ["", "12", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable11_14 = ["", "13", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable11_15 = ["", "14", "n1x", "0", "rte", "0", "0", "0", "ac", "", "", "0", ""],
        dialCodeTable11_total = [0, dialCodeTable11_1, dialCodeTable11_2, dialCodeTable11_3, dialCodeTable11_4, dialCodeTable11_5, dialCodeTable11_6, dialCodeTable11_7, dialCodeTable11_8, dialCodeTable11_9, dialCodeTable11_10, dialCodeTable11_11, dialCodeTable11_12, dialCodeTable11_13, dialCodeTable11_14, dialCodeTable11_15];