function RedcomDatabaseTableConfig() {


    var RedcomDatabaseTableConfigTable = "";

    RedcomDatabaseTableConfigTable += "<table id='RedcomSliceGenerationTable' class='terminalTables'>";
    RedcomDatabaseTableConfigTable += "<tr class='greyTD centerTD'>";
    RedcomDatabaseTableConfigTable += "<td colspan='7' class='centerTD'>DATABASE TABLE CONFIGURATION</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>Bytes in database</td>";
    RedcomDatabaseTableConfigTable += "<td>Used: 407816</td>";
    RedcomDatabaseTableConfigTable += "<td>Free: 392184</td>";
    RedcomDatabaseTableConfigTable += "<td>&nbsp;</td>";
    RedcomDatabaseTableConfigTable += "<td>&nbsp;</td>";
    RedcomDatabaseTableConfigTable += "<td>&nbsp;</td>";
    RedcomDatabaseTableConfigTable += "<td>&nbsp;</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td width='5%'>TABLE</td>";
    RedcomDatabaseTableConfigTable += "<td width='3%'>CURR</td>";
    RedcomDatabaseTableConfigTable += "<td width='2%'>min</td>";
    RedcomDatabaseTableConfigTable += "<td width='3%'>max</td>";
    RedcomDatabaseTableConfigTable += "<td width='3%'>size</td>";
    RedcomDatabaseTableConfigTable += "<td width='4%'>scope</td>";
    RedcomDatabaseTableConfigTable += "<td width='80%'>COMMENT</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>aflst</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>5</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>750</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>56</td>";
    RedcomDatabaseTableConfigTable += "<td>msu</td>";
    RedcomDatabaseTableConfigTable += "<td>Regular STN ANI feature lists</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>afmem</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>50</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>5000</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>23</td>";
    RedcomDatabaseTableConfigTable += "<td>msu</td>";
    RedcomDatabaseTableConfigTable += "<td>Regular STN ANI feature entries</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>agent</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>3</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>7</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>36</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>SNMP Agent Configurations</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>attribute</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>255</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>35</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Attribute tables</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>block</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>100</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1600</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Block setting for port connections</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>budgets</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>20</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>200</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>4</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Budgets Table</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>change</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>10</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>500</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>29</td>";
    RedcomDatabaseTableConfigTable += "<td>msu</td>";
    RedcomDatabaseTableConfigTable += "<td>Change number intercept</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>class</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>20</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>500</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>34</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Class features services (0)</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>cled</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>400</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>40</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Console LED map</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>connect</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>100</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1600</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Connect setting for trunks</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>cron</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>150</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>201</td>";
    RedcomDatabaseTableConfigTable += "<td>msu</td>";
    RedcomDatabaseTableConfigTable += "<td>Cron timer entries</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>cusdb</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>9999</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>20</td>";
    RedcomDatabaseTableConfigTable += "<td>msu</td>";
    RedcomDatabaseTableConfigTable += "<td>Custom database information</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>daflst</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>5</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1000</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>56</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Dynamic STN ANI feature lists</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>dafmem</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>50</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>5000</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>23</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Dynamic STN ANI feature lists</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>dcta</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>20</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>250</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>59</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Dial table attributes</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>dctm</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>5</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1000</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>56</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Dynamic STN ANI feature lists</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>dev</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>46</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>10</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1000</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>102</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>System device configurations</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>domain</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>10</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>255</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>4</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>MLPP domain number table</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>dstint</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>2</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1000</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>303</td>";
    RedcomDatabaseTableConfigTable += "<td>msu</td>";
    RedcomDatabaseTableConfigTable += "<td>Dynamic Station Information</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>dtrmem</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>8</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>64</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>426</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>DB transaction definition</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>dwake</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>2</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1000</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>8</td>";
    RedcomDatabaseTableConfigTable += "<td>msu</td>";
    RedcomDatabaseTableConfigTable += "<td>Dynamic wake-up tables</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr>";
    RedcomDatabaseTableConfigTable += "<td>fblist</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>20</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>1</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>100</td>";
    RedcomDatabaseTableConfigTable += "<td class='rightTD'>24</td>";
    RedcomDatabaseTableConfigTable += "<td>network</td>";
    RedcomDatabaseTableConfigTable += "<td>Feature button list table</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "<tr class='greyTD centerTD'>";
    RedcomDatabaseTableConfigTable += "<td colspan='2'>MSU= 0/0</td>";
    RedcomDatabaseTableConfigTable += "<td colspan='3'>VERBOSE= off</td>";
    RedcomDatabaseTableConfigTable += "<td>&nbsp;</td>";
    RedcomDatabaseTableConfigTable += "<td>&nbsp;</td>";
    RedcomDatabaseTableConfigTable += "<td>&nbsp;</td>";
    RedcomDatabaseTableConfigTable += "</tr>";
    RedcomDatabaseTableConfigTable += "</table>";


    return RedcomDatabaseTableConfigTable;

}